AWSTemplateFormatVersion: 2010-09-09
Description: Crafter AWS resources for the environment

Parameters:
  Environment:
    Type: String
  S3BucketNamePrefix:
    Type: String
  CloudFrontLoggingS3BucketName:
    Type: String

Resources:
  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for all Crafter CloudFronts of the ${Environment} environment'

  CloudFrontLoggingS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref CloudFrontLoggingS3BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  S3ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${S3BucketNamePrefix}-*"
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource: !Sub "arn:aws:s3:::${S3BucketNamePrefix}-*/*"

Outputs:
  CloudFrontOriginAccessIdentityId:
    Value: !Ref CloudFrontOriginAccessIdentity
  S3ReplicationRoleArn:
    Value: !GetAtt [S3ReplicationRole, Arn]