description: External Secrets Operator and Secret Stores
name: external-secrets
version: 1.16
dependencies:
  - name: external-secrets
    version: 1.1.1
    repository: https://charts.external-secrets.io