description: External Secrets Operator and Secret Stores
name: external-secrets
version: 1.18
dependencies:
  - name: external-secrets
    version: 2.0.1
    repository: https://charts.external-secrets.io