description: External Secrets Operator and Secret Stores
name: external-secrets
version: 1.11
dependencies:
  - name: external-secrets
    version: 0.14.2
    repository: https://charts.external-secrets.io