apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - install.yaml
patches:
  - path: patches.yaml
  # STAGE2_NLB_KUSTOMIZE_START
  # - path: patches-nlb.yaml
  # STAGE2_NLB_KUSTOMIZE_END